Update mainn.yml

diff --git a/.github/workflows/mainn.yml b/.github/workflows/mainn.yml
--- a/.github/workflows/mainn.yml
+++ b/.github/workflows/mainn.yml
@@ -57,16 +57,20 @@ jobs:
           Get-ChildItem "C:\Users\Public\Desktop" | Where-Object { $_.Name -match "Azure|Assure|Unity" } | Remove-Item -Force -Recurse -ErrorAction SilentlyContinue
           Get-ChildItem "C:\ProgramData\Microsoft\Windows\Start Menu\Programs" -Recurse | Where-Object { $_.Name -match "Azure|Assure|Unity" } | Remove-Item -Force -Recurse -ErrorAction SilentlyContinue
 
-      # -------------------- NGROK PART --------------------
-
       - name: Download ngrok
         run: |
           Invoke-WebRequest https://bin.equinox.io/c/bNyj1mQVY4c/ngrok-v3-stable-windows-amd64.zip -OutFile ngrok.zip
           Expand-Archive ngrok.zip -DestinationPath ngrok
 
       - name: Configure ngrok
+        env:
+          NGROK_AUTH_TOKEN: ${{ secrets.NGROK_AUTH_TOKEN }}
         run: |
-          .\ngrok\ngrok.exe config add-authtoken $Env:NGROK_AUTH_TOKEN
+          if (-not $env:NGROK_AUTH_TOKEN) {
+            Write-Error "NGROK_AUTH_TOKEN is missing"
+            exit 1
+          }
+          .\ngrok\ngrok.exe config add-authtoken $env:NGROK_AUTH_TOKEN
 
       - name: Start ngrok TCP tunnel for RDP
         run: |
